language: cpp

branches:
  only: 
    - master

env:
- PYTHON_BUILD_VERSION=3.7

dist: xenial
sudo: false

addons:
  apt:
    packages:
    - git 
    - cmake 
    - build-essential 
    - libxmu-dev 
    - libxi-dev 
    - xorg-dev
    - freeglut3-dev 
    - libglfw3-dev 
    - libglew-dev
    - python3-dev 
    - python3-pip
    - python3-setuptools

script: |
  git submodule init
  git submodule update

###########
# test cpp
  cd test_cpp/googletest
  cmake .
  make
  cd ../../

  cd test_cpp
  mkdir buildMake
  cd buildMake
  cmake ..
  make
  make test 
  ./runUnitTests
  cd ../../

###########################
# build c++ glut examples
  cd examples_glut
  mkdir buildMake
  cd buildMake
  cmake ..
  make -i
  cd ../..

###########################
# build C++ glfw examples
  cd examples_glfw/glfw
  cmake .
  make
  cd ../..

  cd examples_glfw
  mkdir buildMake
  cd buildMake
  cmake ..
  make -i
  cd ../..

############################
# build python module
  pyenv versions
  pyenv global 3.7
  python --version  

  cd src_pybind/core
  mkdir buildMake
  cd buildMake
  cmake ..
  make    
  cd ../../../

  cd src_pybind/gl
  mkdir buildMake
  cd buildMake
  cmake ..
  make    
  cd ../../../

  cd src_pybind/eigen
  mkdir buildMake
  cd buildMake
  cmake ..
  make    
  cd ../../../

  pip3 install --upgrade pip setuptools
  pip3 install -e .  

###########################
# test python module
  pip3 install pytest
  pytest -v -s --is_gl=false --ignore=test_py/test_pyqt.py