language: cpp

branches:
  only: 
    - master

env:
- PYTHON_BUILD_VERSION=3.7

dist: xenial
sudo: false

addons:
  apt:
    packages:
    - git 
    - cmake 
    - build-essential 
    - libxmu-dev 
    - libxi-dev 
    - xorg-dev
    - freeglut3-dev 
    - libglfw3-dev 
    - libglew-dev

script: |
  git submodule update --init --recursive

  echo "# --------------------------"
  echo "# build c++ glut examples"
  cd examples_oldgl_glut
  mkdir buildMake && cd buildMake
  cmake ..
  make
  cd ../..

  echo "# ----------------"
  echo "# fetch googletext"
  git submodule update --init -- 3rd_party/googletest
  cd 3rd_party/googletest
  cmake .
  make
  cd ../../

  echo "# ----------------"
  echo "# build test"
  cd test_cpp
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=OFF ..
  make
  make test 
  ./runUnitTests
  cd ../../

  cd test_cpp
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=ON ..
  make
  make test 
  ./runUnitTests
  cd ../../


  echo "# -------------------------"
  echo "# build C++ oldGL glfw examples"
  git submodule update --init -- 3rd_party/glfw
  cd 3rd_party/glfw
  cmake .
  make
  cd ../..

  cd examples_oldgl_glfw
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../..

  cd examples_oldgl_glfw
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=OFF ..
  make
  cd ../..

  echo "# -------------------------"
  echo "# build C++ newGL glfw examples"
  cd examples_newgl_glfw
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../..

  cd examples_newgl_glfw
  mkdir buildMakeStatic && cd buildMakeStatic
  cmake -DUSE_HEADERONLY=OFF ..
  make
  cd ../..

  echo "# -------------------------"
  echo "# build tinyglfw examples"
  cd examples_oldgl_glfw_tinygltf
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../../

  echo "# --------------------------"
  echo "# build glfw_thread examples"
  cd examples_oldgl_glfw_thread
  mkdir buildMakeHdronly && cd buildMakeHdronly
  cmake -DUSE_HEADERONLY=ON ..
  make
  cd ../../  